/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import course.Course;
import course.CourseCollection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leila
 */
public class CourseSearchPanel extends javax.swing.JPanel {

    CourseCollection courses;

    DefaultTableModel table_model;
    String[] tableHeader = {"Reference", "Title", "Fees"};

    /**
     * Creates new form CourseSearchPanel
     */
    public CourseSearchPanel() {
        table_model = new DefaultTableModel();
        table_model.setColumnIdentifiers(tableHeader);
        initComponents();
        courses = new CourseCollection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        maxFeesTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        searchBtn = new javax.swing.JButton();

        jLabel2.setText("Find courses with maximum amount of fees");

        jLabel3.setText("Maximum Fees:");

        maxFeesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxFeesTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Search Results");

        searchResultsTable.setModel(table_model);
        jScrollPane1.setViewportView(searchResultsTable);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(maxFeesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(163, 163, 163))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxFeesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maxFeesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxFeesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxFeesTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:

        String maxFees = maxFeesTxt.getText();
        if (maxFees.isEmpty()) {
            JOptionPane.showMessageDialog(CourseSearchPanel.this, "Please enter a valid entry.",
                    "Search courses", JOptionPane.ERROR_MESSAGE);
            //idk what the third arg is
            return;
        }
        Double maxFeesDouble = null;
        try {
            maxFeesDouble = Double.parseDouble(maxFees);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(CourseSearchPanel.this, "Entry must be a number!",
                    "Search courses", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // normal execution: search for courses
        ArrayList<Course> searchResults = courses.findCoursesWithFees(maxFeesDouble);
        // video says to import static GUI.CourseraGUI.courses ??
        if(searchResults.isEmpty()){
            table_model.setDataVector(null, tableHeader);
            JOptionPane.showMessageDialog(CourseSearchPanel.this, "No courses with less than this amount of fees.",
                    "Search courses", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // create data vector: 2d array
        // rows are courses
        // column 1 is ref, 2 is title, 3 is fees
        Object [][] tableData = new Object[searchResults.size()][tableHeader.length];
        for (int i=0; i < searchResults.size(); i++){
            Course c = searchResults.get(i);
            tableData[i][0] = c.getReference();
            tableData[i][1] = c.getTitle();
            tableData[i][2] = c.getFees();
        }
        // tableData is built
        table_model.setDataVector(tableData, tableHeader);
        
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField maxFeesTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable searchResultsTable;
    // End of variables declaration//GEN-END:variables
}
